# -*- coding: utf-8 -*-

def main():
    startApplication("Calculator")
    clickButton(waitForObject(":MainWindow.btnClear_QPushButton"))
    test.compare(str(waitForObjectExists(":MainWindow.label_QLabel").text), "0")
    sendEvent("QMoveEvent", waitForObject(":MainWindow_MainWindow"), 1062, 34, 1229, 44)
    clickButton(waitForObject(":MainWindow.btnPercentage_QPushButton"))
    sendEvent("QMoveEvent", waitForObject(":MainWindow_MainWindow"), 674, 166, 799, 176)
    clickButton(waitForObject(":MainWindow.btnNum1_QPushButton"))
    test.compare(str(waitForObjectExists(":MainWindow.label_QLabel").text), "1")
    clickButton(waitForObject(":MainWindow.btnNum2_QPushButton"))
    test.compare(str(waitForObjectExists(":MainWindow.label_QLabel").text), "12")
    clickButton(waitForObject(":MainWindow.btnNum3_QPushButton"))
    test.compare(str(waitForObjectExists(":MainWindow.label_QLabel").text), "123")
    clickButton(waitForObject(":MainWindow.btnNum4_QPushButton"))
    test.compare(str(waitForObjectExists(":MainWindow.label_QLabel").text), "1234")
    clickButton(waitForObject(":MainWindow.btnNum5_QPushButton"))
    test.compare(str(waitForObjectExists(":MainWindow.label_QLabel").text), "12345")
    clickButton(waitForObject(":MainWindow.btnNum6_QPushButton"))
    test.compare(str(waitForObjectExists(":MainWindow.label_QLabel").text), "123456")
    clickButton(waitForObject(":MainWindow.btnNum7_QPushButton"))
    test.compare(str(waitForObjectExists(":MainWindow.label_QLabel").text), "1234567")
    clickButton(waitForObject(":MainWindow.btnNum8_QPushButton"))
    test.compare(str(waitForObjectExists(":MainWindow.label_QLabel").text), "12345678")
    clickButton(waitForObject(":MainWindow.btnNum9_QPushButton"))
    test.compare(str(waitForObjectExists(":MainWindow.label_QLabel").text), "123456789")
